(function(){'use strict';
const $=id=>document.getElementById(id),Story=window.NightStory,Atlas=window.NightAtlas,Game=window.NightGame,I18n=window.NightI18n,Release=window.NightRelease,KEY='unfinished-night-save-v1';
let game=new Game(),active=false,target=null,arrival=null,lastTime=0,toastTimer,storageOK=true,audioCtx=null,audioGain=null,audioTimer=null,audioOn=false;
const keys=new Set();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const saved=localStorage.getItem(KEY);if(saved)game=new Game(JSON.parse(saved))}catch(e){storageOK=false;setTimeout(()=>toast('先前存檔無法讀取，或瀏覽器不允許儲存。可用匯入／下載存檔保存旅程。'),400)}
function toast(message){
 const dialog=[$('story-dialog'),$('journal-dialog')].find(d=>d.open);
 if(dialog){let notice=dialog.querySelector('.dialog-notice');if(!notice){notice=document.createElement('p');notice.className='dialog-notice';notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');notice.setAttribute('aria-atomic','true');dialog.append(notice)}notice.textContent=message;notice.scrollIntoView({block:'nearest'});return}
 $('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').classList.remove('show');$('toast').textContent=''},4800)
}
function save(){if(!game.state.started&&!game.state.blank_trust_stage)return;try{localStorage.setItem(KEY,JSON.stringify(game.state));storageOK=true}catch(e){if(storageOK)toast('此瀏覽器無法自動存檔。請從手記下載存檔。');storageOK=false}}
const tr=text=>I18n.t(text);
const chapterAt=i=>I18n.isEnglish()?I18n.chapters[i]:Story.chapters[i];
const nodeLabel=(chapter,id,fallback)=>{if(!I18n.isEnglish())return fallback;const index=Story.chapters[chapter]?.nodes.findIndex(n=>n[0]===id)??-1;return index>=0?I18n.nodes[chapter][index]:fallback};
function localizeView(original){if(!I18n.isEnglish()||!original)return original;const view={...original,choices:(original.choices||[]).map(c=>({...c,label:I18n.action[c.id]||tr(c.label),detail:c.detail&&!/[\u3400-\u9fff]/.test(c.detail)?c.detail:undefined}))};
 const chapter=game.state.chapter,ch=Story.chapters[chapter],en=I18n.chapters[chapter];
 if(original.nodeId){view.speaker=nodeLabel(chapter,original.nodeId,original.speaker);view.text=I18n.scene(chapter,original.nodeId)||original.text}
 else if(ch&&(original.speaker===ch.title||original.speaker.endsWith(' · '+ch.title))){view.speaker=en.title;view.text=en.intro}
 else if(original.puzzle?.kind==='ending'){view.speaker='Ending · The Canvas Remains Wet';view.text=['You chose without claiming that choice would remain perfect forever. The people inside the frame now have a place in every future revision.','Starwheel Town, the wheatfield, Sunflower Court and the blue room retain the consequences of what you decided. None has been reduced to a simple right answer.','Ink settles on your shoulder. “How many people today?” he asks. You begin to count, and he listens.','The canvas is still wet. This time, unfinished can also be a form of hope.','Part One ends here. The distant realms remain under construction.'];}
 if(view.puzzle)view.puzzle={...view.puzzle};
 return view}
function title(){active=false;cancelMove();paintLanguage();$('title-screen').hidden=false;$('game-screen').hidden=true;$('continue-btn').hidden=!game.state.started;$('continue-btn').textContent=I18n.isEnglish()?(game.state.finished?'Return to the completed journey':'Continue your journey'):(game.state.finished?'回到已完成的旅程':'繼續上次的旅程');const ch=chapterAt(Math.min(game.state.chapter,4));$('save-info').textContent=I18n.isEnglish()?(game.state.started?(game.state.chapter>=5?'A later-part save is preserved · Part One is currently open':game.state.finished?'Part One complete · five chapters preserved':'Journey paused at Chapter '+ch.roman+' · '+ch.title):'Five painted realms · one traveller · one crow who remembers you'):(game.state.started?(game.state.chapter>=5?'已保留第二部存檔 · 目前開放第一部五章':game.state.finished?'第一部五章已完成 · 旅程仍留在畫境':'旅程停在第 '+ch.roman+' 章 · '+ch.title):'五幅畫境 · 一位旅人 · 一隻記得你的烏鴉');$('start-btn').textContent=I18n.isEnglish()?(game.state.started?'Begin a new journey':'Enter the painting ↗'):(game.state.started?'開始一段新旅程':'走進畫裡 ↗')}
function archive(){show({speaker:I18n.isEnglish()?'A journey beyond this release':'這段旅程來自尚未開放的遠方',text:I18n.isEnglish()?['This save has reached Chapters VI–VIII, which remain in development. It has not been changed or overwritten.','Download a copy now, then begin or import a Part One journey when you are ready.']:['這份存檔已走到第六至八章；那些章節仍在製作，因此目前不開放遊玩。存檔沒有被降級或覆寫。','請先下載備份。之後第二部重新開放時，仍可帶回這段旅程。'],choices:[{id:'export',label:I18n.isEnglish()?'Download this save':'下載這份存檔'},{id:'cancel',label:I18n.isEnglish()?'Return to title':'回到標題'}]},{export:()=>{download();return null},cancel:()=>null})}
function enter(){if(game.state.chapter>=Release.chapters){archive();return}active=true;$('title-screen').hidden=true;$('game-screen').hidden=false;render();$('world').focus({preventScroll:true})}
function newGame(){const stage=game.state.started?0:game.state.blank_trust_stage;game=new Game();game.state.blank_trust_stage=stage;enter();show(game.start());save()}
function cancelMove(){target=null;keys.clear();if(arrival){arrival(false);arrival=null}setMotion(false,0)}
function render(){
 const ch=game.chapter,s=game.state;const art=$('scene-art');if(art.dataset.image!==ch.image){art.dataset.image=ch.image;art.style.backgroundImage='url("assets/'+ch.image+'")';art.style.animation='none';void art.offsetWidth;art.style.animation=''}
 const display=chapterAt(s.chapter),mood=s.choices['c'+(s.chapter+1)];$('world').className=mood?'mood-'+mood:'';$('chapter-index').textContent='CHAPTER '+ch.roman+' / V';$('chapter-title').textContent=display.title;$('chapter-subtitle').textContent=display.subtitle;$('quest-text').textContent=I18n.isEnglish()?I18n.objective(s):game.objective();$('memory-count').textContent=s.memories.length;$('crow-line').textContent=I18n.isEnglish()?(s.finished?'Your turn to count today. I would like to rest.':s.choices['c'+(s.chapter+1)]?'Your choice has become part of this place. Go and see what followed.':display.line):(s.finished?'今天換你數。我想休息一下。':s.choices['c'+(s.chapter+1)]?'你做的選擇，已經成為這裡的一部分。去看看他們吧。':ch.line);
 const nav=$('chapter-nav');nav.replaceChildren();Story.chapters.slice(0,Release.chapters).forEach((c,i)=>{const el=document.createElement('button');el.className='chapter-dot'+(i===s.chapter?' current':'')+(s.choices['c'+(i+1)]?' complete':'');const dc=chapterAt(i);el.textContent=c.roman;el.title=dc.title;el.setAttribute('aria-label',(I18n.isEnglish()?'Chapter ':'第 ')+c.roman+' '+dc.title+(i>s.chapter?(I18n.isEnglish()?', not yet reached':'，尚未抵達'):''));if(i===s.chapter)el.setAttribute('aria-current','step');el.disabled=i>s.chapter;el.onclick=()=>show({speaker:dc.title,text:[dc.subtitle,dc.question,i===s.chapter?(I18n.isEnglish()?I18n.objective(s):game.objective()):(I18n.isEnglish()?'Your choice: '+I18n.choices[s.choices['c'+(i+1)]]:'你的選擇：'+Story.choiceNames[s.choices['c'+(i+1)]])],choices:[]});nav.append(el)});
 renderRegions();
 const marks=$('hotspots');marks.replaceChildren();game.mapNodes.forEach(([id,label,x,y,icon])=>{label=nodeLabel(s.chapter,id,label);const btn=document.createElement('button');btn.className='hotspot';const prefix='c'+(s.chapter+1)+'_';if(game.has(prefix+'visited_'+id))btn.classList.add('visited');if(s.chapter>=5&&id==='source'&&game.has(prefix+'borrowed')&&!game.has(prefix+'returned'))btn.classList.add('source-empty');if(s.chapter>=5&&id==='after'&&mood)label='回訪 · '+ch.title;if((id==='lamp'&&game.has('c1_yellow')&&!game.has('c1_letter'))||(id==='well'&&game.has('c1_blue')&&!game.has('c1_keeper'))||(s.chapter===4&&['yellow','blue','green'].includes(id)&&game.has('c5_'+id)))btn.classList.add('source-empty');btn.style.left=x+'%';btn.style.top=y+'%';btn.dataset.node=id;btn.setAttribute('aria-label','探索'+label);const mark=document.createElement('span');mark.className='hotspot-mark';const inner=document.createElement('span');inner.textContent=icon;inner.setAttribute('aria-hidden','true');mark.append(inner);const name=document.createElement('span');name.className='hotspot-label';name.textContent=label;btn.append(mark,name);btn.onclick=e=>{e.stopPropagation();moveTo(x,y+5,id)};marks.append(btn)});
 const colors=$('pigments');colors.replaceChildren();[['yellow','黃','#e8c360'],['blue','藍','#649ad8'],['green','綠','#6ca790']].forEach(([id,label,color])=>{const el=document.createElement('div');el.className='pigment'+(game.carries(id)?' held':'');el.style.setProperty('--pigment',color);el.title=label+'：'+(game.carries(id)?'攜帶中':'未攜帶');el.setAttribute('aria-label',el.title);el.setAttribute('role','img');const tip=document.createElement('span');tip.textContent=label;el.append(tip);colors.append(el)});updatePosition();
}
function updatePosition(){const p=game.state.position;$('traveler').style.left=p.x+'%';$('traveler').style.top=p.y+'%'}
function setMotion(moving,dx){const t=$('traveler');t.classList.toggle('walking',moving);if(dx>0.02){t.classList.add('dir-right');t.classList.remove('dir-left')}else if(dx<-0.02){t.classList.add('dir-left');t.classList.remove('dir-right')}}
function paragraphs(element,text){element.replaceChildren();text.forEach(t=>{const p=document.createElement('p');p.textContent=t;element.append(p)})}
function openTrust(overview=false){cancelMove();const previous=game.view;window.NightTrust.open(game.state,stage=>{game.sealTrust(stage);save()},{overview,onClose:()=>{
 if(!overview&&previous?.resonanceNode&&$('story-dialog').open){
  const base={...previous,text:previous.text.slice(0,previous.marginStart),marginIds:[]};
  const view=window.NightResonance.decorate(game.state,previous.resonanceNode,true,base);
  view.trustIds=window.NightTrust.at(game.state,view.resonanceNode,true);game.view=view;show(view);
 }
}})}
function show(view,handlers){window.NightLoreTrust.stop();if(!view){$('story-dialog').close();render();save();return}view=localizeView(view);cancelMove();const d=$('story-dialog');d.querySelector('.dialog-notice')?.remove();$('toast').textContent='';$('toast').classList.remove('show');$('dialog-speaker').textContent=view.speaker;$('dialog-kicker').textContent=view.puzzle?.kind==='ending'?(I18n.isEnglish()?'THE UNFINISHED NIGHT · FINALE':'THE UNFINISHED NIGHT · 終章'):(I18n.isEnglish()?'A VOICE IN THE PAINTED REALM':'畫境裡的聲音');paragraphs($('dialog-text'),view.text);$('dialog-choices').replaceChildren();$('puzzle-area').replaceChildren();
 for(const choice of view.choices||[]){const button=document.createElement('button');button.textContent=choice.label;if(choice.detail){const detail=document.createElement('small');detail.textContent=choice.detail;button.append(detail)}button.onclick=()=>{try{const next=handlers?handlers[choice.id]():game.choose(choice.id);if(next&&view.nodeId&&!next.nodeId)next.nodeId=view.nodeId;render();save();if(next!==undefined)show(next,next?.handlers);else d.close()}catch(e){toast(e.message)}};$('dialog-choices').append(button)}
 if(view.puzzle&&view.puzzle.kind!=='ending')renderPuzzle(view.puzzle);
 if(!view.choices?.length&&!view.puzzle){const button=document.createElement('button');button.textContent=I18n.isEnglish()?'Close and keep exploring':'收起話語，繼續探索';button.onclick=()=>d.close();$('dialog-choices').append(button)}
 if(view.puzzle?.kind==='ending'){const mark=document.createElement('div');mark.className='ending-mark';mark.textContent='FIN';$('puzzle-area').append(mark)}
 if(view.loreId&&!I18n.isEnglish()){const entry=Atlas.entries.find(e=>e.id===view.loreId),more=document.createElement('button');more.className='lore-question';more.textContent='追問：'+entry.title;more.onclick=()=>show({speaker:entry.speaker,text:entry.text,choices:[{id:'return-story',label:'回到剛才的對話'}]},{'return-story':()=>view});$('dialog-choices').append(more)}
 for(const id of view.trustIds||[]){const b=document.createElement('button');b.className='trust-invitation';b.textContent=I18n.isEnglish()?'Open voluntarily · Blank Trust':'自願開啟 · 空白信託';b.onclick=()=>{cancelMove();openTrust()};$('dialog-choices').append(b)}
 paginateDialogue(view);if(!d.open)d.showModal();d.scrollTop=0;const focus=$('dialog-pagination').querySelector('.next-page')||$('dialog-choices').querySelector('button')||$('puzzle-area').querySelector('button')||$('close-dialog');focus.focus({preventScroll:true});save();
}
function renderPuzzle(p){
 const area=$('puzzle-area'),numeric=p.kind==='allocation',assigned=p.kind==='assignment',selected=p.kind==='selection';
 const count=p.count||p.length||3,total=p.total||6,unit=p.unit||(p.id==='ferry'?'塊木板':'份光');
 let values=numeric?p.items.map(()=>0):assigned?p.rows.map(()=>null):[];
 const feedback=document.createElement('p');feedback.className='puzzle-feedback';feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');feedback.setAttribute('aria-atomic','true');
 const report=message=>{feedback.textContent=I18n.isEnglish()&&/[\u3400-\u9fff]/.test(message)?'That does not fit the evidence yet. Recheck the notebook or ask Ink for a clue; a wrong answer costs nothing.':message;feedback.scrollIntoView({block:'center',behavior:'auto'})};
 const display=document.createElement('div');display.className='sequence-display';display.setAttribute('aria-live','polite');area.append(display);
 const controls=document.createElement('div');controls.className='puzzle-grid';area.append(controls);
 const update=()=>{
  display.textContent=I18n.isEnglish()?(numeric?'Assigned '+values.reduce((a,b)=>a+b,0)+' / '+total:assigned?'Arranged '+values.filter(v=>v!==null).length+' / '+p.rows.length:selected?'Selected '+values.length+' / '+count:values.length?values.map(x=>I18n.items[x]||x).join(' → '):'Choose an order · · ·'):(numeric?'已分配 '+values.reduce((a,b)=>a+b,0)+' / '+total+' '+unit:assigned?'已安排 '+values.filter(v=>v!==null).length+' / '+p.rows.length+' 項':selected?'已選 '+values.length+' / '+count+' 項':values.length?values.join(' → '):'選擇順序 · · ·');
  if(numeric)controls.querySelectorAll('output').forEach((o,i)=>o.textContent=values[i]);
  if(selected)controls.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-pressed',String(values.includes(i))));
 };
 if(assigned){
  controls.classList.add('assignment-grid');p.rows.forEach((label,i)=>{
   const row=document.createElement('div');row.className='assignment-row';const name=document.createElement('label'),select=document.createElement('select');
   select.id='assign-'+p.id+'-'+i;name.htmlFor=select.id;name.textContent=I18n.isEnglish()?(I18n.items[label]||label):label;const blank=document.createElement('option');blank.value='';blank.textContent=I18n.isEnglish()?'Choose':'選擇安排';select.append(blank);
   p.items.forEach((item,j)=>{const o=document.createElement('option');o.value=String(j);o.textContent=item;select.append(o)});
   select.onchange=()=>{values[i]=select.value===''?null:Number(select.value);update()};row.append(name,select);controls.append(row);
  });
 }else if(p.kind==='sequence'||selected){
  p.items.forEach((item,i)=>{const btn=document.createElement('button');btn.textContent=I18n.isEnglish()?(I18n.items[item]||item):item;
   btn.onclick=()=>{if(selected&&values.includes(i))values=values.filter(v=>v!==i);else if(values.length<count)values.push(selected?i:item);else report('已選滿 '+count+' 項；可以取消選取或清除後重排。');update()};controls.append(btn);
  });
 }else{
  controls.style.display='block';p.items.forEach((label,i)=>{
   const row=document.createElement('div');row.className='allocation-row';const name=document.createElement('span');name.textContent=I18n.isEnglish()?(I18n.items[label]||label):label;const counter=document.createElement('div');counter.className='counter';
   const minus=document.createElement('button'),plus=document.createElement('button'),out=document.createElement('output');minus.textContent='−';plus.textContent='+';
   minus.setAttribute('aria-label',label+'減少一'+unit);plus.setAttribute('aria-label',label+'增加一'+unit);out.setAttribute('aria-label',label+'目前數量');
   minus.onclick=()=>{values[i]=Math.max(0,values[i]-1);update()};plus.onclick=()=>{if(values.reduce((a,b)=>a+b,0)<total){values[i]++;update()}else report('只有 '+total+' '+unit+'。請先從另一處減少。')};
   counter.append(minus,out,plus);row.append(name,counter);controls.append(row);
  });
 }
 const buttons=document.createElement('div');buttons.className='save-actions';const reset=document.createElement('button'),submit=document.createElement('button'),hint=document.createElement('button');
 reset.className='secondary';reset.textContent=I18n.isEnglish()?'Clear and reorder':'清除重排';reset.onclick=()=>{values=numeric?p.items.map(()=>0):assigned?p.rows.map(()=>null):[];controls.querySelectorAll('select').forEach(select=>select.value='');feedback.textContent='';update()};
 submit.className='primary';submit.textContent=I18n.isEnglish()?(assigned?'Confirm arrangement':selected?'Check this evidence':numeric?'Confirm allocation':'Join the memories'):(assigned?'確認安排':selected?'核對這些依據':numeric?'確認分配':'讓記憶接合');
 submit.onclick=()=>{try{const result=game.solve(values);if(result.ok){render();save();show(result.view)}else{report(result.message);if(p.kind==='sequence'){values=[];update()}}}catch(e){report(e.message)}};
 hint.className='text-btn';hint.textContent=I18n.isEnglish()?'Ask Ink for a hint':'請墨給一點提示';let hintStage=0;
 const clue=document.createElement('p');clue.className='puzzle-clue';clue.setAttribute('aria-live','polite');clue.setAttribute('aria-atomic','true');
 hint.onclick=()=>{
  const vague={stars:'墨歪著頭：「信和索恩各記得一半。試著把兩個「比誰先」接起來。」',roads:'墨用喙碰了碰羽毛：「旅人只見過後半段；泥殼的內外層可以補上前半段。」',lights:'墨說：「答案就攤在帳簿那一頁，你只是還沒仔細讀。」',memories:'墨壓低聲音：「鏡子最擅長的，就是把發生的順序換一遍。」',weave:'墨說：「三種顏色，各自擅長不同的事。想想它們平常做什麼。」'};
  const full={stars:Story.memories.letter.text,roads:Story.memories.footprints.text,lights:Story.memories.ledger.text,memories:Story.memories.draft.text,weave:'先以藍凝止崩解，再以綠接合裂口，最後以黃照見彼此。'};
  const vagueEn={stars:'Ink tilts his head. “The letter and Soren each preserve half. Join the two accounts of what came first.”',roads:'Ink taps the feather. “The traveller saw the latter part; the feather’s inner and outer layers preserve the earlier part.”',lights:'Ink says, “The answer is in the ledger. Read the three needs separately.”',memories:'Ink lowers his voice. “Mirrors excel at reversing the order of events.”',weave:'Ink says, “Each colour has one limited function. Begin by stopping the collapse.”',repairs:'Use load-bearing material for the eaves, rope for the bridge, and light only as a marker.',anchors:'Choose traces that can be cross-checked in two places.',compact:'Keep basic light after withdrawal and make the accounts public.',clock:'Separate a promise from a verifiable past and a companion present now.',ferry:'The craft marks say three boards for the deck, two for return markers and two for the shared record.'};
  const fullEn={stars:I18n.memories.letter[1],roads:I18n.memories.footprints[1],lights:I18n.memories.ledger[1],memories:I18n.memories.draft[1],weave:'Blue arrests the collapse; green joins the fracture; yellow lets people see one another.',repairs:'Timber supports the eaves; rope secures the bridge; the shaded lamp marks the meeting place.',anchors:'Blue mud and old clock-gold are physical traces of the route.',compact:'Keep basic lighting after withdrawal, and publish the light accounts every week.',clock:'The unsigned letter is an unverified promise; the underpainting is a checkable past; the three knocks are a companion in the present.',ferry:'Three boards for the deck, two for return markers, and two for the shared record: seven in all.'};
  if(hintStage===0){clue.textContent=I18n.isEnglish()?(vagueEn[p.id]||'Return to the notebook and separate evidence from hope.'):(p.hint||vague[p.id])+'（再按一次可看完整線索）';hintStage=1;hint.textContent=I18n.isEnglish()?'Read the full clue':'重讀完整線索'}else clue.textContent=I18n.isEnglish()?(fullEn[p.id]||'Recheck each recorded requirement.'):(p.clue||full[p.id]);
  clue.scrollIntoView({block:'nearest'});
 };buttons.append(submit,reset,hint);area.append(feedback,buttons,clue);update();
}
function renderRegions(){
 const goal=game.goal;$('chapter-phase').textContent=goal?goal.stage:'既有旅程 · 本章沿用原流程';
 const nav=$('region-nav');nav.replaceChildren();game.regions.forEach((region,i)=>{
  const btn=document.createElement('button');btn.textContent=I18n.isEnglish()?(game.state.region===i?'Area '+(i+1)+' · Current':'Area '+(i+1)):region.name;btn.className='region-button';btn.setAttribute('aria-pressed',String(i===game.state.region));
  if(goal&&game.regionFor(goal.node)===i){const marker=document.createElement('span');marker.textContent=' · 線索';marker.className='region-hint';btn.append(marker)}
  btn.onclick=()=>switchRegion(i);nav.append(btn);
 });$('world').dataset.region=String(game.state.region);
 $('mobile-goal').textContent=I18n.isEnglish()?I18n.objective(game.state):game.objective();
 $('scene-art').style.backgroundPosition=game.state.region===1?'68% center':'center';
}
function switchRegion(index){cancelMove();try{game.setRegion(index);render();save();$('world').focus({preventScroll:true})}catch(e){toast(e.message)}}
function paginateDialogue(view){
 const container=$('dialog-pagination'),area=$('puzzle-area'),choices=$('dialog-choices');container.replaceChildren();let page=0;const size=2,pages=Math.max(1,Math.ceil(view.text.length/size));
 const paint=()=>{
  window.NightLoreTrust.stop();
  paragraphs($('dialog-text'),view.text.slice(page*size,(page+1)*size));container.replaceChildren();area.hidden=choices.hidden=page<pages-1;
  [...$('dialog-text').children].forEach((el,i)=>{if(page*size+i>=view.marginStart){el.classList.add('resonance-ink');}});
  if(page===pages-1){for(const flag of view.marginIds||[])game.flag(flag);save();
   if(view.bellEvidence){const proof=document.createElement('section');proof.className='resonance-proof';
    for(const spec of window.NightResonance.checks){const detail=document.createElement('details'),summary=document.createElement('summary'),text=document.createElement('p');summary.textContent=spec.title;text.textContent=spec.text;detail.append(summary,text);proof.append(detail)}
    if(game.state.blank_trust_stage>=6){const prompt=document.createElement('p');prompt.textContent='再找一次：有沒有什麼紀錄，會使目前的解釋站不住？';proof.append(prompt)}
    $('dialog-text').append(proof);
   }
  }
  if(pages>1){
   const prev=document.createElement('button'),label=document.createElement('span'),next=document.createElement('button');prev.className='text-btn';prev.textContent=I18n.isEnglish()?'Previous':'上一段';prev.disabled=page===0;
   label.textContent=(page+1)+' / '+pages;label.className='fine';label.setAttribute('aria-live','polite');
   prev.onclick=()=>{page--;paint();$('story-dialog').scrollTop=0};container.append(prev,label);
   if(page<pages-1){next.className='secondary next-page';next.textContent=I18n.isEnglish()?'Keep reading':'繼續讀';next.onclick=()=>{page++;paint();$('story-dialog').scrollTop=0;($('dialog-pagination').querySelector('.next-page')||choices.querySelector('button')||area.querySelector('button,select')||$('close-dialog')).focus({preventScroll:true})};container.append(next)}
  }
  [...$('dialog-text').children].forEach((el,i)=>{
   if(view.inkIndices?.includes(page*size+i)){const text=el.textContent,host=document.createElement('div');el.replaceWith(host);window.NightLoreTrust.mount(host,text);}
  });
 };paint();
}
function inspect(id){try{const revisited=game.has('c'+(game.state.chapter+1)+'_visited_'+id);const view=game.interact(id),entry=Atlas.at(game.state,id);view.nodeId=id;view.trustIds=window.NightTrust.at(game.state,id,revisited);if(id.startsWith('record_')&&!game.has('c'+(game.state.chapter+1)+'_evidence_'+id.slice(-1)))view.trustIds=[];if(entry)view.loreId=entry.id;render();show(view);save()}catch(e){toast(e.message)}}
function moveTo(x,y,node){if(!active||$('story-dialog').open||$('journal-dialog').open||$('trust-dialog').open)return Promise.resolve(false);cancelMove();target={x:Math.max(5,Math.min(95,x)),y:Math.max(23,Math.min(91,y)),node};if(reduced){game.state.position={x:target.x,y:target.y};updatePosition();target=null;if(node)inspect(node);save();return Promise.resolve(true)}return new Promise(resolve=>{arrival=resolve})}
function tick(now){const dt=Math.min((now-lastTime)/1000||0,.06);lastTime=now;if(active&&!$('story-dialog').open&&!$('journal-dialog').open&&!$('trust-dialog').open){const p=game.state.position;let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('a'))dx--;if(keys.has('ArrowRight')||keys.has('d'))dx++;if(keys.has('ArrowUp')||keys.has('w'))dy--;if(keys.has('ArrowDown')||keys.has('s'))dy++;
 if(dx||dy){if(target){target=null;if(arrival){arrival(false);arrival=null}}const n=Math.hypot(dx,dy);p.x=Math.max(5,Math.min(95,p.x+dx/n*dt*23));p.y=Math.max(23,Math.min(91,p.y+dy/n*dt*30));updatePosition();setMotion(true,dx)}
 else if(target){const tdx=target.x-p.x,tdy=target.y-p.y,dist=Math.hypot(tdx,tdy),step=dt*42;if(dist<=step){p.x=target.x;p.y=target.y;const node=target.node;target=null;updatePosition();setMotion(false,0);const done=arrival;arrival=null;if(node)inspect(node);save();if(done)done(true)}else{p.x+=tdx/dist*step;p.y+=tdy/dist*step;updatePosition();setMotion(true,tdx)}}
 else setMotion(false,0);
}requestAnimationFrame(tick)}
function appendAtlas(content){
 const heading=document.createElement('h3');heading.textContent='畫境志';heading.className='journal-chapter';content.append(heading);
 const found=Atlas.available(game.state),intro=document.createElement('p');intro.className='fine';intro.textContent='已發現 '+found.length+' / '+Atlas.entries.length+' 篇 · 地標裡聽來的故事與尚待查證的傳聞。';content.append(intro);
 for(const entry of found){const section=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('div');section.className='atlas-entry';summary.textContent=entry.title;paragraphs(body,entry.text);section.append(summary,body);content.append(section)}
}
function journal(){cancelMove();$('journal-dialog').querySelector('.dialog-notice')?.remove();const content=$('journal-content');content.replaceChildren();const en=I18n.isEnglish();$('journal-title').textContent=en?'Traveller’s notebook':'旅人手記';if(game.goal){const task=document.createElement('p');task.className='journal-task';task.textContent=en?I18n.objective(game.state):game.goal.stage+' · '+game.objective();content.append(task)}Story.chapters.slice(0,Release.chapters).forEach((c,i)=>{if(i>game.state.chapter)return;const h=document.createElement('h3');h.className='journal-chapter';h.textContent=c.roman+' / '+chapterAt(i).title;content.append(h);const found=game.state.memories.filter(k=>Story.memories[k].chapter===i);if(!found.length){const p=document.createElement('p');p.className='fine';p.textContent=en?'This page is still waiting for a story.':'這一頁，還在等待故事。';content.append(p)}for(const k of found){const m=en?I18n.memories[k]:[Story.memories[k].title,game.memoryText(k)],card=document.createElement('article'),heading=document.createElement('h3'),p=document.createElement('p');card.className='memory-card';heading.textContent=m[0];p.textContent=m[1];card.append(heading,p);content.append(card)}if(!en)for(const note of window.NightResonance.journal(game.state,i)){const card=document.createElement('article'),heading=document.createElement('h3');card.className='memory-card resonance-note';heading.textContent=note.title;card.append(heading);const body=document.createElement('div');paragraphs(body,note.text);card.append(body);content.append(card)}const chosen=game.state.choices['c'+(i+1)];if(chosen){const p=document.createElement('p');p.className='fine';p.textContent=en?'Choice left behind: '+I18n.choices[chosen]:'留下的選擇：'+Story.choiceNames[chosen];content.append(p)}});if(!en)appendAtlas(content);else{const p=document.createElement('p');p.className='fine';p.textContent='Part Two atlas records remain sealed during this five-chapter release.';content.append(p)}$('journal-dialog').showModal()}
function download(){const blob=new Blob([JSON.stringify(game.state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='unfinished-night-journey.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('旅程存檔已準備下載。')}
function help(){show(I18n.isEnglish()?{speaker:'How to travel through the painted realm',text:['Click a landmark to walk toward it and open its scene. You can also move with WASD or the arrow keys and press E near a landmark. On phones, tap a landmark or use Places; Movement opens touch controls.','Each chapter has two areas. A clue marker identifies the area containing your next objective. The current objective changes as you investigate. Ask Ink when you are stuck; puzzles also provide a clue button.','Borrowing colour temporarily changes its source. After a repair, colour is returned or given a new place. There are no timers.','Your journey saves automatically in this browser. Download the JSON save from the notebook before changing devices. Press Escape to close a dialogue.'],choices:[]}:{speaker:'如何在畫境裡旅行',text:['點擊地標，旅人會走近並開啟對話。也可用 WASD 或方向鍵移動，靠近地標後按 E；手機可直接點地標，或用底部「地點清單」前往；「方向鍵」可展開移動與互動按鈕。','每章有兩個探索區域，可從畫面上方切換；標有「線索」的區域包含下一項目標。畫面右上的「當前線索」會隨進度改變。卡住時按「問問墨」；謎題裡也能重讀線索。','借色會暫時改變來源。完成修復後，顏色會歸還或安放到新位置。選擇沒有倒數，請慢慢讀。','旅程會自動儲存在這個瀏覽器。從「旅人手記」下載存檔，就能換到另一台裝置繼續。按 Esc 可關閉對話。'],choices:[]})}
function sound(){if(audioOn){audioOn=false;clearInterval(audioTimer);if(audioGain)audioGain.gain.setTargetAtTime(0,audioCtx.currentTime,.5);$('sound-btn').textContent='♫';$('sound-btn').setAttribute('aria-label','開啟環境音');return}try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();if(!audioCtx){audioCtx=new AC();audioGain=audioCtx.createGain();audioGain.gain.value=0;audioGain.connect(audioCtx.destination)}audioCtx.resume();audioOn=true;audioGain.gain.setTargetAtTime(.11,audioCtx.currentTime,.5);const play=()=>{if(document.hidden)return;const t=audioCtx.currentTime,notes=[146.83,174.61,220,261.63,293.66];[0,1,2].forEach((n)=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=notes[(game.state.chapter+n*2)%notes.length];gain.gain.setValueAtTime(0,t+n*.8);gain.gain.linearRampToValueAtTime(.12,t+n*.8+1.5);gain.gain.exponentialRampToValueAtTime(.001,t+n*.8+6);osc.connect(gain);gain.connect(audioGain);osc.start(t+n*.8);osc.stop(t+n*.8+7)})};play();audioTimer=setInterval(play,7000);$('sound-btn').textContent='♪';$('sound-btn').setAttribute('aria-label','關閉環境音')}catch(e){toast('這個瀏覽器暫時無法播放環境音。')}}
$('start-btn').onclick=()=>{if(game.state.started)show({speaker:'開始一段新旅程？',text:['目前的自動存檔會被新旅程取代。可以先下載存檔，保留這一次的選擇。'],choices:[{id:'export',label:'先下載目前存檔'},{id:'new',label:'開始新旅程，取代自動存檔'},{id:'cancel',label:'保留目前旅程'}]}, {export:()=>{download();return null},new:()=>{$('story-dialog').close();newGame();return game.view},cancel:()=>null});else newGame()};
$('continue-btn').onclick=()=>{if(game.state.chapter>=Release.chapters){archive();return}enter();if(game.state.finished)show(game.ending())};$('home-btn').onclick=()=>{save();title()};$('help-btn').onclick=help;$('journal-btn').onclick=journal;$('hint-btn').onclick=()=>{const goal=game.goal,region=goal?game.regionFor(goal.node):-1,en=I18n.isEnglish();show({speaker:en?'Ink’s hint':'墨的提示',text:[en?I18n.objective(game.state):game.objective(),region>=0?(en?'The next clue is in Area '+(region+1)+'. '+(region!==game.state.region?'Switch areas above the painting.':'You are already in that area.'):'線索在「'+game.regions[region].name+'」。'+(region!==game.state.region?'可以從畫面上方切換區域。':'你已經在這個區域。')):(en?'Everything you have collected is in the notebook.':'你收集過的文字都在旅人手記。')],choices:region>=0&&region!==game.state.region?[{id:'region',label:en?'Go to Area '+(region+1):'前往'+game.regions[region].name}]:[]},{region:()=>{switchRegion(region);return null}})};$('sound-btn').onclick=sound;
$('close-dialog').onclick=()=>$('story-dialog').close();$('close-journal').onclick=()=>$('journal-dialog').close();for(const id of ['story-dialog','journal-dialog'])$(id).addEventListener('close',()=>{window.NightLoreTrust.stop();if(active)$('world').focus({preventScroll:true});render();save()});
$('about-btn').onclick=()=>show(I18n.isEnglish()?{speaker:'About this unfinished world',text:['The Unfinished Night is an original fantasy exploration game inspired by the emotional movement of Van Gogh’s paintings. This public release contains five complete chapters; Chapters VI–VIII remain in development.','Its rules, characters and events are fictional. They do not claim to represent Van Gogh’s biography or the single correct reading of his work. The scenes and crow are original AI-generated painted assets, not digital copies of existing paintings.','Created by Lin Hsuan-Yu, with story and game production developed in collaboration with AI. The journey has no combat or time limit and requires no AI account or API.'],choices:[]}:{speaker:'關於這個尚未乾透的世界',text:['《未乾之夜》是一款以梵谷繪畫為靈感的原創奇幻探索遊戲。本次封盤開放星夜、麥田、向日葵、藍色房間與空白海五章；第六至八章仍在製作。','畫境規則、角色與事件均為原創虛構，不代表梵谷的生平或畫作的唯一解讀。場景與烏鴉為 AI 生成的原創繪畫素材，並非原作數位複製品。','創作發起：林萱渝。故事與遊戲製作：與 AI 協作。沒有戰鬥與時間限制，遊玩不需要 AI 帳號或 API。'],choices:[]});
$('export-btn').onclick=download;for(const id of ['import-btn','import-title'])$(id).onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>100000)throw Error('存檔檔案太大。請選擇遊戲匯出的 JSON 存檔。');const candidate=new Game(JSON.parse(await file.text()));if(candidate.state.chapter>=Release.chapters)throw Error(I18n.isEnglish()?'This save belongs to Part Two, which is still in development. The file remains unchanged and your current journey was not replaced.':'這份存檔屬於仍在製作的第二部。原檔沒有改變，目前旅程也未被取代。');$('journal-dialog').close();show(I18n.isEnglish()?{speaker:'Load this journey?',text:['This will load the saved journey at “'+chapterAt(candidate.state.chapter).title+'” and replace the current browser save.'],choices:[{id:'load',label:'Load this save'},{id:'cancel',label:'Keep the current journey'}]}:{speaker:'載入這段旅程？',text:['即將載入「'+candidate.chapter.title+'」的旅程，取代目前瀏覽器內的自動存檔。'],choices:[{id:'load',label:'載入這份存檔'},{id:'cancel',label:'保留目前旅程'}]},{load:()=>{game=candidate;save();enter();toast('旅程已載入。');return game.state.finished?game.ending():null},cancel:()=>null})}catch(err){toast(err.message||'無法讀取這份存檔。')}};
$('world').addEventListener('click',e=>{if(e.target.closest('button')||e.target.closest('.color-palette'))return;const r=$('world').getBoundingClientRect();moveTo((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)});
window.addEventListener('keydown',e=>{if(!active||$('story-dialog').open||$('journal-dialog').open||$('trust-dialog').open||e.target.closest('button,input'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(key)){e.preventDefault();keys.add(key)}if(key==='e'){e.preventDefault();nearby()}});window.addEventListener('keyup',e=>{keys.delete(e.key.length===1?e.key.toLowerCase():e.key);if(active)save()});window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();save()}});window.addEventListener('beforeunload',save);
for(const btn of document.querySelectorAll('[data-dir]')){const key={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[btn.dataset.dir];btn.onpointerdown=e=>{e.preventDefault();keys.add(key);btn.setPointerCapture(e.pointerId)};btn.onpointerup=btn.onpointercancel=()=>{keys.delete(key);save()}}
for(let i=0;i<14;i++){const dot=document.createElement('i');dot.className='mote';dot.style.left=(7+i*6.5)%100+'%';dot.style.top=(30+i*13)%93+'%';dot.style.animationDelay=(-i*.9)+'s';$('motes').append(dot)}
// Optional structured access uses the same visible journey state. No AI runtime dependency.
const context=document.modelContext;if(context?.registerTool){const controller=new AbortController();for(const tool of [{name:'read_journey',title:'讀取畫境旅程',description:'Read the current chapter, objective and collected memories without changing the journey.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');return {chapter:game.chapter.title,objective:game.objective(),memories:game.state.memories.map(k=>Story.memories[k].title),finished:game.state.finished}}}]){try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch(e){}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
// Every visible circular star, the moon and both whorls share a slow sky current.
const skyCircles=[[110,70,70],[398,94,63],[691,35,35],[1086,39,39],[563,230,70],[753,306,74],[1340,119,119],[944,208,135],[1140,322,83]];
const skyLayer=$('title-screen').querySelector('.title-sky');
const skyMaxR=Math.max(...skyCircles.map(c=>c[2]));
skyCircles.forEach((circle,i)=>{const el=document.createElement('div');el.className='sky-vortex'+(circle[2]===skyMaxR?' sky-vortex-main':'');el.dataset.sky=String(i);el.style.animationDuration=Math.round(70+circle[2]*0.6)+'s';skyLayer.append(el)});
function alignSky(){
 const art=$('title-screen').querySelector('.title-art'),r=art.getBoundingClientRect();if(!r.width||!r.height)return;
 const pos=getComputedStyle(art).backgroundPosition.split(' ').map(parseFloat),scale=Math.max(r.width/1536,r.height/1024);
 const ox=(r.width-1536*scale)*(pos[0]/100),oy=(r.height-1024*scale)*(pos[1]/100);
 skyLayer.querySelectorAll('.sky-vortex').forEach((el,i)=>{const [x,y,radius]=skyCircles[i],left=(x-radius)*scale,top=(y-radius)*scale;Object.assign(el.style,{left:(ox+left)+'px',top:(oy+top)+'px',width:(radius*2*scale)+'px',height:(radius*2*scale)+'px',backgroundSize:(1536*scale)+'px '+(1024*scale)+'px',backgroundPosition:(-left)+'px '+(-top)+'px'});el.style.setProperty('--glow-delay',(-i*.65)+'s')});
 Object.assign(skyLayer.querySelector('.sky-current').style,{left:ox+'px',top:oy+'px',width:(1536*scale)+'px',height:(1024*scale)+'px'});
}
const skyObserver=new ResizeObserver(alignSky);skyObserver.observe($('title-screen'));window.addEventListener('resize',alignSky);
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');let skyPaused=motionQuery.matches;
function updateSky(){const stopped=skyPaused||motionQuery.matches;$('title-screen').classList.toggle('sky-paused',stopped);$('sky-motion-btn').textContent=stopped?'播放星空':'暫停星空';$('sky-motion-btn').setAttribute('aria-pressed',String(!stopped));$('sky-motion-btn').disabled=motionQuery.matches;if(motionQuery.matches)$('sky-motion-btn').textContent='星空已靜止'}
$('sky-motion-btn').onclick=()=>{skyPaused=!skyPaused;updateSky()};motionQuery.addEventListener('change',updateSky);updateSky();
$('trust-title').onclick=()=>openTrust(true);
function loreIndexView(){
 return I18n.isEnglish()?{speaker:'The Residual Realm · A world still wet',text:['The painted realms are joined by unfinished strokes. Fractures sometimes bring distant places together, and no single painter owns the whole world.','Borrowed colours have limits: yellow reveals, blue arrests, and green joins. When colour is borrowed, its source temporarily loses that function.','Objects and crows may preserve fragments of memory, but cannot replace a whole person. Evidence can support an account of the past; it cannot decide another person’s future.','Part One contains five playable chapters. The records of the Ochre Salt Market, Snowbell City and Glass Tides remain sealed while Part Two is being built.'],choices:[]}:{speaker:'餘彩域 · 未乾的世界',text:[...Atlas.overview.slice(0,4),'目前封盤版開放第一部五章。赤赭鹽市、雪鈴城與玻璃潮汐的地標紀錄暫時封存，待第二部完成後開放。'],choices:[]};
}
function loreEntryView(id){
 const entry=window.NightLoreTrust.lookup(game.state,id);
 if(!entry)return null;
 return {speaker:entry.title,text:entry.annotation?[...entry.facts,entry.annotation]:entry.facts,inkIndices:entry.annotation?[entry.facts.length]:[],choices:[{id:'lore-back',label:'回到餘彩域地標目錄'}],handlers:{'lore-back':loreIndexView}};
}
$('atlas-title').onclick=()=>{const view=loreIndexView();show(view,view.handlers);};
$('mobile-journal').onclick=journal;$('mobile-hint').onclick=()=>$('hint-btn').click();
$('movement-toggle').onclick=()=>{const panel=$('touch-controls');panel.hidden=!panel.hidden;$('movement-toggle').setAttribute('aria-expanded',String(!panel.hidden))};
$('places-btn').onclick=()=>{const nodes=game.mapNodes,handlers={};nodes.forEach(([id,label,x,y])=>{handlers[id]=()=>{$('story-dialog').close();moveTo(x,y+5,id)}});show({speaker:'本區地點',text:['點選名稱，旅人就會前往並開啟對話。切換區域可從地圖上方選擇。'],choices:nodes.map(([id,label])=>({id,label:(game.goal?.node===id?'當前線索 · ':'')+label}))},handlers)};
function nearby(){const p=game.state.position,near=game.mapNodes.map(n=>({n,d:Math.hypot(n[2]-p.x,n[3]+5-p.y)})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<18)inspect(near.n[0]);else toast('再靠近一個地標，或從地點清單選擇它。')}
$('touch-interact').onclick=nearby;
for(const btn of document.querySelectorAll('[data-dir]'))btn.onlostpointercapture=()=>{keys.clear();setMotion(false,0);save()};
function paintLanguage(){const en=I18n.isEnglish();document.documentElement.lang=en?'en':'zh-Hant';$('language-btn').textContent=en?'中文':'English';$('game-language-btn').textContent=en?'中':'EN';for(const id of ['language-btn','game-language-btn'])$(id).setAttribute('aria-label',en?'切換至中文':'Switch to English');
 $('sky-motion-btn').textContent=en?(skyPaused?'Play sky':'Pause sky'):(skyPaused?'播放星空':'暫停星空');$('about-btn').textContent=en?'About':'關於畫境';document.querySelector('.eyebrow').textContent=en?'Before the canvas dries, let us walk a little farther.':'在畫布乾透以前，讓我們再走遠一點。';document.querySelector('.title-copy h1').textContent=en?'The Unfinished Night':'未乾之夜';document.querySelector('.title-copy .intro').innerHTML=en?'On the night the stars stopped turning,<br>a crow asked you to remember tomorrow.':'星星不再轉動的那晚，<br>一隻烏鴉，請你替牠記住明天。';$('atlas-title').textContent=en?'Explore the Residual Realm':'認識餘彩域';$('trust-title').textContent=en?'Blank Trust · Questions on paper':'空白信託 · 紙上的提問';$('import-title').textContent=en?'Import journey save':'匯入旅程存檔';document.querySelector('.title-bottom span:first-child').textContent=en?'EXPLORE / BORROW COLOUR / REMEMBER':'探索 / 借色 / 記憶';
 $('journal-btn').childNodes[0].nodeValue=en?'Notebook ':'旅人手記 ';$('help-btn').setAttribute('aria-label',en?'How to play':'操作說明');$('home-btn').setAttribute('aria-label',en?'Return to title':'返回主選單');$('places-btn').textContent=en?'Places':'地點清單';$('mobile-journal').textContent=en?'Notebook':'旅人手記';$('mobile-hint').textContent=en?'Ask Ink':'問問墨';$('movement-toggle').textContent=en?'Movement':'方向鍵';$('hint-btn').textContent=en?'Ask Ink ↗':'問問墨 ↗';document.querySelector('.phase-label').textContent=en?'JOURNEY PROGRESS':'旅程進展';document.querySelector('.quest span').textContent=en?'CURRENT CLUE':'當前線索';document.querySelector('.palette-label').textContent=en?'BORROWED COLOURS':'借來的色彩';document.querySelector('.speaker-small').textContent=en?'INK · KEEPER OF FRAGMENTS':'墨 · 拾遺者';$('map-hint').textContent=en?'WASD / arrows to move · E to interact · Tab for landmarks':'WASD／方向鍵移動 · E 互動 · Tab 選地標';}
function toggleLanguage(){I18n.set(I18n.isEnglish()?'zh-Hant':'en');paintLanguage();if(active)render();else title()}
$('language-btn').onclick=toggleLanguage;$('game-language-btn').onclick=toggleLanguage;
title();alignSky();requestAnimationFrame(tick);
})();

