(function(root){'use strict';
const KEY='unfinished-night-language';
const chapters=[
 {title:'Starwheel Town',subtitle:'A star that refuses to be repaired',question:'How much tomorrow are we willing to surrender for safety?',line:'Are you trying to get there, or to get there safely? Those are two different questions.',intro:['You meant only to mend a crack in a painting. Now turpentine has become the night wind, and the stone road beneath you is still wet.','A crow lands on the signpost. “Do not step on that stroke. It was painted only yesterday.” It studies you, then resumes counting the people behind the windows.','Every clock in town has stopped at 11:59. Far away, the lampmaker waves as though he has been waiting a long time.']},
 {title:'The Forking Wheatfield',subtitle:'Even a road without choice has been walked',question:'Is the road we did not take truly better?',line:'Do not ask me which road is best. Ask those who left footprints which road they walked.',intro:['Beyond the town, wheat rises like a golden sea. When you look back, the road to Starwheel Town has moved behind another hill.','“The roads here read faces,” Ink says. “Whenever you hesitate, they grow another branch.”','Three crows guard the fork. Each claims to have seen the lampmaker’s daughter, and each points elsewhere.']},
 {title:'Sunflower Court',subtitle:'Who pays for this world’s happiness?',question:'How does a society that refuses sorrow treat the wounded?',line:'They say no one cries here. Is that happiness, or nowhere left to cry?',intro:['Summer never ends in Sunflower Court. Every flower faces a tower of artificial light, while residents arrange bottles of golden memories in a tidy row.','A notice at the gate reads: “Surrender one happy memory. Help us remain bright.”','You hear someone crying beyond the hedge. Ink lowers his head and presses a feather containing the sound of rain into your palm.']},
 {title:'The Room That Waits',subtitle:'A room that knows your heart too well',question:'Does missing a place mean that you should remain there forever?',line:'You may rest. I will knock on the window. Answer me when you hear the third knock.',intro:['Beyond the door is a blue room. The cup on the table is warm; a coat in exactly your size hangs from the chair.','You know this is not your home, yet suddenly cannot remember how home differs. The door becomes a painting behind you.','Ink stays outside the window. “If it feels too comfortable, look beneath the bed. Rooms seldom clean their underpainting properly.”']},
 {title:'The Blank Sea',subtitle:'Before the final stroke is laid down',question:'When you can alter another person’s world, what counts as repair?',line:'If I forget, tell me once. It need not be forever. Only this once.',intro:['The sea has no fixed shore. Half-painted houses, half a letter, and colourless trees drift through white tides.','Every fracture opens here. In the distance stands an easel holding no ending, only a blank space that still waits.','Light begins to pass through Ink’s wings. He says he is not cold, yet for the first time loses count of those behind him.']}
];
const nodes=[
 ['The lampmaker’s lamp','The stalled star','The still-blue well','The faded letter','The clocktower watchman','Path to the wheatfield','Names Square','Riverbank Workshop'],
 ['The traveller without a shadow','The three-faced signpost','The mud-stained feather','Brook and reflection','The moving fork','The wanderer’s campfire','Garden boundary','Fallen Waymarkers','Reply Post'],
 ['The keeper of the court','The child who refuses','The ledger of light','The light cistern','Three dividing lamps','The crow who kept the rain','The blue door','Duty Board','Seedling Shelter'],
 ['The unsent letter','The underpainting beneath the bed','The borrowed mirror','The third knock','Three overlapping paintings','The vanished exit','The Traveller’s Luggage','The Clock by the Door'],
 ['The first easel','The lost gold','The arrested tide','The unfinished shoot','The world’s fracture','Ink and your name','The final stroke','Drifting Letter Post','The Unclaimed Ferry']
];
const regions=[['Town Street & Star Clock','Riverbank & Clocktower'],['Forks in the Wheat','The Wanderer’s Bank'],['The Long-Summer Court','The Shaded Garden'],['The Room’s Surface','Window & Underpainting'],['Drifting Canvases','The Unnamed Shore']];
const phases={'一 · 借來的光':'I · Borrowed Light','二 · 保存的代價':'II · The Cost of Keeping','三 · 決定之前':'III · Before the Decision','四 · 留在街上的痕跡':'IV · Traces Left in the Street','一 · 不可靠的承諾':'I · An Unreliable Promise','二 · 腳印與倒影':'II · Footprints and Reflections','三 · 回頭的條件':'III · The Conditions for Returning','四 · 收信的人':'IV · The One Who Receives the Letter','一 · 長夏的帳單':'I · The Account of Long Summer','二 · 光足夠，誰仍在哭':'II · When Light Is Enough, Who Still Weeps','三 · 能夠說不的約定':'III · An Agreement That Allows Refusal','四 · 改變以後的第一夜':'IV · The First Night After Change','一 · 太熟悉的陌生地方':'I · A Place Strangely Familiar','二 · 底稿會留下什麼':'II · What the Underpainting Keeps','三 · 誰正在叫你的名字':'III · Who Is Calling Your Name','四 · 真正出發的動作':'IV · The Act of Truly Leaving','一 · 畫者沒有寫下的答案':'I · The Answer the Painter Never Wrote','二 · 先使世界能夠呼吸':'II · First, Let the World Breathe','三 · 聽見畫框的另一端':'III · Hear the Other Side of the Frame','四 · 最後一筆屬於誰':'IV · Who Owns the Final Stroke','終 · 畫布仍未乾透':'Finale · The Canvas Remains Wet'};
const memories={
 letter:['An Unsent Tomorrow','Aila wrote: “Father, I was not taken. I want to know what lies beyond the wheatfield. If the clock stops again, please do not mistake waiting for my consent.” In the margin is the star-clock order: first the lamp in the window, then the moon in the water, and finally the star above.'],
 clock:['The Watchman’s Seven-Hundredth Repair','The first fracture swallowed three streets. The watchman stopped time one minute before the disaster and saved the town, but repeated repairs slowly erased names. A method of preservation can also become harm.'],
 footprints:['Soil Is More Reliable Than Promises','Aila’s pack carries blue mud from the brook and old gold dust from the clock in a feather. Her route reads: first hear the brook, then see the old clock, finally face the distant hill. The road marked “safest” has no footprints.'],
 daughter:['A Person Has the Right to Leave','Aila is alive. Leaving was her choice. She will send word that she is safe, but will not promise to return at once. She wants her father to receive the truth, not a comforting false promise.'],
 ledger:['The Accounts of a Long Summer','The cistern produces six shares of light each day: two for seedlings, three for homes, and one for roads. Survival needs exactly six. Permanent summer requires additional memories; it is not the only way the residents can live.'],
 rain:['The Rain That Was Hidden','The happiness the child refuses to surrender is the memory of listening to rain with his dead mother. Removing it would also cut the thread by which he understands grief. The crow will return the memory so the residents can choose how to preserve it.'],
 draft:['The Order Beneath the Room','The underpainting records three moments: first the painter rescued an injured crow; then the painted realm was born; finally the painter left and the crow gathered the memories left behind. The mirror reverses them, turning waiting into an endless command.'],
 name:['The Name Ink Once Had','The remembered call came from the person who rescued him. He was first named Return, but now chooses to keep the name you gave him. Being remembered does not require living as someone else expected.'],
 painter:['The Rules the Painter Left','The realm was never dry and could always fracture. Forcing eternal night, endless summer and perpetual waiting made repairable cracks deepen. The painter left no single ending. Both structure and rules must be changed with the residents.'],
 promise:['Taking Turns to Remember','A crow has only so many feathers; no one person can preserve everything. You and Ink agree to give these stories to more people willing to listen. Forgetting is not indifference, but preservation cannot rest on one life alone.']
};
const choices={night:'Continue the starry night for now, with informed consent',dawn:'Prepare together and welcome dawn',letter:'Send Aila’s truthful letter',beacon:'Repair the markers and keep both places connected',seasons:'Let the seasons return',consent:'Keep summer through a voluntary, revocable rota',rest:'Carry the memories, rest, and then leave',release:'Set down the past the room prepared',restore:'Repair the frame and create shared stewardship',open:'Open the boundary for free passage',share:'Give the brush to the residents'};
const action={
 explore:'Begin exploring',back:'Return to the realm and see what changed',reveal:'Reveal the faded writing with yellow',freeze:'Arrest the fracture with blue','record-town':'Make the first shared record with the residents','hear-fear':'Ask what those who stayed need in order to prepare','hear-loss':'Ask how erased names should be kept together',deliver:'Deliver only the message its author consented to send',care:'Complete the immediate care with the residents',pack:'Put away your own draft and leave the unsigned promise',margin:'Keep the correction and the reason for uncertainty',blank:'Leave the name blank and record only verifiable facts','return-council':'Continue hearing the others','council-agree':'Preserve all four conditions and a method for correction','borrow-yellow':'Borrow the yellow light','borrow-blue':'Borrow the blue','borrow-mirror':'Borrow the blue from the mirror','send-letter':'Send her truthful letter','build-beacon':'Repair the two-way markers together','collect-light':'Guide all six shares into the divider',night:'Continue the night for now',dawn:'Prepare for dawn',seasons:'Let the four seasons return',consent:'Keep summer with a voluntary rota',rest:'Rest one night, then leave with the memories',release:'Set down the past prepared by the room',restore:'Repair the frame and build shared stewardship',open:'Open the boundary for free passage',share:'Give the brush to the residents',next:'Continue onward','epilogue-close':'Remain in the realm and open the notebook',export:'Download the current save first',new:'Begin anew and replace the browser save',cancel:'Keep the current journey',load:'Load this save',region:'Go to the marked area','return-story':'Return to the conversation','lore-back':'Return to the atlas index'};
const items={'星':'Star','燈':'Lamp','月':'Moon','鐘':'Clock','遠山':'Distant hill','舊鐘':'Old clock','溪水':'Brook','路牌':'Signpost','育苗燈':'Seedling lamps','住屋燈':'Home lamps','路燈':'Road lamps','畫者離開':'The painter leaves','救下烏鴉':'The crow is rescued','畫境誕生':'The painted realm is born','永遠等待':'Wait forever','黃':'Yellow','綠':'Green','藍':'Blue','鞋底的藍泥':'Blue mud on the sole','羽毛上的舊鐘金粉':'Old clock-gold on the feather','路牌寫著最安全':'The sign marked “safest”','溪水映出的理想人生':'An ideal life reflected by the brook','遮光燈':'Shaded lamp','木梁':'Timber beam','繩索':'Rope','撐住屋簷':'Support the eaves','固定橋面':'Secure the bridge deck','標示集合點':'Mark the meeting place','退出後仍保有基本照明':'Basic light remains after withdrawal','每週公開光的收支':'Publish the light accounts weekly','交付後不能撤回':'No withdrawal after giving','付出最多的人免於檢查':'The greatest contributor is exempt from review','此刻的同行者':'A companion present now','無法核實的承諾':'An unverifiable promise','可核對的往事':'A checkable past','沒有署名的信':'The unsigned letter','床下的底稿':'The underpainting beneath the bed','窗外三次敲擊':'Three knocks at the window','承重甲板':'Load-bearing deck','返航標記':'Return markers','共同紀錄板':'Shared record board'};
const ui={
 '暫停星空':'Pause sky','播放星空':'Play sky','星空已靜止':'Sky motion reduced','關於畫境':'About','在畫布乾透以前，讓我們再走遠一點。':'Before the canvas dries, let us walk a little farther.','星星不再轉動的那晚，':'On the night the stars stopped turning,','一隻烏鴉，請你替牠記住明天。':'a crow asked you to remember tomorrow.','走進畫裡 ↗':'Enter the painting ↗','走進畫裡':'Enter the painting','繼續上次的旅程':'Continue your journey','回到已完成的旅程':'Return to the completed journey','認識餘彩域':'Explore the Residual Realm','空白信託 · 紙上的提問':'Blank Trust · Questions on paper','匯入旅程存檔':'Import journey save','旅人手記':'Traveller’s notebook','問問墨 ↗':'Ask Ink ↗','問問墨':'Ask Ink','地點清單':'Places','方向鍵':'Movement','互動':'Interact','當前線索':'Current clue','旅程進展':'Journey progress','借來的色彩':'Borrowed colours','畫境裡的聲音':'A voice in the painted realm','收起話語，繼續探索':'Close and keep exploring','關閉對話':'Close dialogue','關閉手記':'Close notebook','下載旅程存檔':'Download journey save','匯入存檔':'Import save','上一段':'Previous','繼續讀':'Keep reading','清除重排':'Clear and reorder','確認安排':'Confirm arrangement','核對這些依據':'Check this evidence','確認分配':'Confirm allocation','讓記憶接合':'Join the memories','請墨給一點提示':'Ask Ink for a hint','重讀完整線索':'Read the full clue','自願開啟 · 空白信託':'Open voluntarily · Blank Trust','回到餘彩域地標目錄':'Return to the atlas index','黃':'Yellow','藍':'Blue','綠':'Green','攜帶中':'carried','未攜帶':'not carried','線索':'clue','你':'You','墨 · 拾遺者':'Ink · Keeper of Fragments'};
const objectives=[
 ['Borrow yellow light from the lampmaker, then examine the faded letter.','Borrow blue from the well and meet the watchman.','Use the letter and testimony to tune the star clock.','Return to the star and decide the town’s future.','Visit the lampmaker, then take the wheatfield path.'],
 ['Find the mud-stained feather and verify the route.','Reconstruct the route from physical traces.','Reach the campfire and hear Aila’s account.','Cross the garden boundary.'],
 ['Read the ledger and identify what life truly requires.','Guide the cistern’s six shares of light into the divider.','Distribute six shares among the three lamps.','Hear the child and the crow who kept the rain.','Return to the lamps and decide the future of summer.','Visit the keeper, then open the blue door.'],
 ['Look beneath the bed for the underpainting.','Borrow blue from the mirror to arrest the illusion.','Restore the true order of the three paintings.','Answer Ink at the window.','Go to the exit and decide how to leave.','Pass through the door that now has a handle.'],
 ['Read the first easel.','Borrow yellow, blue and green from the Blank Sea.','Use the three colours in order to mend the fracture.','Complete the promise to take turns remembering.','Lay down the final stroke.','All five chapters are complete. Remember to download your journey save.']
];
function objective(state){const f=k=>!!state.flags[k],c=state.choices,n=state.chapter;if(n===0)return c.c1?objectives[0][4]:!f('c1_letter')?objectives[0][0]:!f('c1_keeper')?objectives[0][1]:f('c1_tuned')?objectives[0][3]:objectives[0][2];if(n===1)return c.c2?objectives[1][3]:!f('c2_feather')?objectives[1][0]:f('c2_path')?objectives[1][2]:objectives[1][1];if(n===2)return c.c3?objectives[2][5]:!f('c3_ledger')?objectives[2][0]:!f('c3_light')?objectives[2][1]:!f('c3_balanced')?objectives[2][2]:(!f('c3_child')||!f('c3_rain'))?objectives[2][3]:objectives[2][4];if(n===3)return c.c4?objectives[3][5]:!f('c4_draft')?objectives[3][0]:!f('c4_blue')?objectives[3][1]:!f('c4_order')?objectives[3][2]:f('c4_name')?objectives[3][4]:objectives[3][3];return state.finished?objectives[4][5]:!f('c5_frame')?objectives[4][0]:!f('c5_woven')?(['yellow','blue','green'].every(x=>state.pigments.includes(x))?objectives[4][2]:objectives[4][1]):f('c5_promise')?objectives[4][4]:objectives[4][3]}
const trust=[
 'If one day you discovered that your deepest pain was part of your personality—even its strongest part—would you still choose to heal it?',
 'What do I truly fear losing: the wound, or the meaning the wound gave me?',
 'If one day you no longer defined yourself through pain, what would remain?',
 'If one day you suddenly felt no pain, how would you recognise that you were still you?',
 'If pain makes you feel real, can you still trust your feelings without it?'
];
const scenes={
 0:['The lampmaker keeps the town lit, but his waiting has hardened into a rule for everyone. His yellow can reveal the faded letter.','The star is bound to the clock. Combine the letter with the watchman’s testimony before deciding whether the town should remain at 11:59.','The well holds a blue that can arrest a fracture long enough to cross it. Borrowing it leaves the water briefly unprotected.','Aila’s faded letter states that leaving was her choice. Yellow light reveals the order of the three star-clocks.','The watchman stopped time to save the town, then kept repeating the repair until names began to wear away. His testimony completes the clock’s order.','This path opens only after the town has made its decision.'],
 1:['This traveller remembers only part of Aila’s route. A recollection can guide inquiry, but cannot complete the evidence alone.','Each face of the sign promises safety. The promise with no footprints is still only a promise.','Blue mud and clock-gold cling to different layers of the feather. Together they record an order no signpost can choose for you.','The brook reflects a beautiful life, but reflections do not prove which road a person walked.','Use the physical traces to reconstruct Aila’s route. A wrong attempt costs no memory.','Aila is alive. She misses her father and still chooses to travel. Help her send truth without turning it into a promise of return.','The way to the next realm opens after Aila has spoken for herself.'],
 2:['The keeper gave much to preserve summer. Her sacrifice does not give her the right to demand the same from everyone else.','The child refuses to surrender a happy memory of rain and his mother. A memory may contain happiness and grief at once.','The ledger separates six shares needed for life from the extra memories demanded by endless summer.','The cistern already holds enough light for seedlings, homes and roads.','Assign two shares to seedlings, three to homes and one to roads, then decide what kind of summer can respect refusal.','This crow hid the sound of rain so grief would still have a place in the garden. Temporary keeping must not be mistaken for ownership.','The blue door waits beyond the decision about summer.'],
 3:['The unsigned letter changes its promise as you reread it. Desire is not evidence of who wrote it.','The underpainting preserves an order: rescue, birth of the realm, departure. The room reverses it to make waiting appear obligatory.','Blue from the mirror can halt its rewriting long enough for the underpainting to be checked.','Ink knocks from the present. Once the past is restored, listen to the companion who is here now.','Place the three events in their evidenced order. “Wait forever” belongs to the illusion, not the record.','The room may offer rest without owning your future. Leaving does not require hating the shelter it gave.'],
 4:['The first easel says to arrest collapse with blue, join the crack with green, then use yellow so people can see one another. It leaves the final decision open.','This gold was borrowed from earlier lights. Its source dims until the colour is placed where it is needed.','Blue buys time for repair; it does not decide the repair itself.','Green joins what was separated, without pretending the pieces were never distinct.','Use blue, green and yellow in that order. Repair stabilises the world; it does not grant authority over its residents.','Ink cannot carry every memory alone. Speak the names you remember and share the burden of keeping them.','Choose who will hold the brush. No choice can guarantee perfection; each must remain answerable to those who live inside the frame.']
};
const expansionScenes={
 0:{square:'The town ledger contains a line worn almost blank. Mara remembers her mother’s gesture, but not her name. Record only what can still be witnessed, and let the blank remain open to later correction.',workshop:'The workshop has one beam, one rope and one shaded lamp. Preparation cannot remove every danger, but each material can be placed where its actual function is needed.'},
 1:{markers:'A road that points only outward can erase the way home. Choose physical traces that can be checked together, then leave markers in both directions.',post:'The reply post preserves consent at both ends. Send only what its author agreed to share; longing does not create a debt of return.'},
 2:{board:'The duty board must say how a resident may refuse, withdraw and inspect the accounts. A voluntary promise is meaningful only while refusal remains possible.',seedlings:'After the decision, the first night still requires care. Protect what truly needs light, permit dormant things to rest, and make the work possible to hand over.'},
 3:{bag:'Your luggage contains a correction once made from guesswork. Keep the reason for uncertainty, or leave the missing name blank and record only what can be verified.',clock:'The clock has confused an unsigned promise, a checkable past and a companion present now. Place each claim where its evidence can actually support it.'},
 4:{council:'People from the earlier realms answer from beyond the frame. Listen to all four conditions before deciding who may hold the brush, and preserve a way to correct the record.',ferry:'Seven boards must make return possible: three for a load-bearing deck, two for return markers and two for a shared record. Light cannot substitute for structure.'}
};
function nodeIndex(chapter,node){const ch=root.NightStory.chapters[chapter];if(!ch)return -1;return [...ch.nodes,...(ch.expansionNodes||[])].findIndex(n=>n[0]===node)}
function scene(chapter,node){if(expansionScenes[chapter]?.[node])return [expansionScenes[chapter][node]];const idx=root.NightStory.chapters[chapter]?.nodes.findIndex(n=>n[0]===node)??-1;return idx>=0?[scenes[chapter][idx]]:null}
let lang='zh-Hant';try{lang=localStorage.getItem(KEY)==='en'?'en':'zh-Hant'}catch(e){}
const api={get lang(){return lang},isEnglish:()=>lang==='en',set(value){lang=value==='en'?'en':'zh-Hant';try{localStorage.setItem(KEY,lang==='en'?'en':'zh-Hant')}catch(e){};document.documentElement.lang=lang;root.dispatchEvent(new CustomEvent('night-language-change'))},t:s=>lang==='en'?(ui[s]||s):s,chapters,nodes,regions,phases,memories,choices,action,items,objective,trust,scene,nodeIndex};
root.NightI18n=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
